# Generated by Django 5.2.16 on 2026-08-05 02:39

import accounts.managers
import accounts.models
import accounts.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, validators=[accounts.validators.validate_birth_date])),
                ('gender', models.CharField(blank=True, choices=[('man', 'Man'), ('woman', 'Woman'), ('other', 'Other')], max_length=20)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=10)),
                ('education_level', models.CharField(blank=True, choices=[('secondary', 'Secondary school'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate or master’s'), ('doctorate', 'Doctorate'), ('vocational', 'Vocational or technical training'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=24)),
                ('field_of_study', models.CharField(blank=True, choices=[('computer_science', 'Computer science'), ('data_science', 'Data science & AI'), ('engineering', 'Engineering'), ('mathematics', 'Mathematics & statistics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology & life sciences'), ('environmental_science', 'Environmental science'), ('medicine', 'Medicine'), ('nursing', 'Nursing & allied health'), ('pharmacy', 'Pharmacy'), ('public_health', 'Public health'), ('psychology', 'Psychology'), ('sociology', 'Sociology & anthropology'), ('economics', 'Economics'), ('business', 'Business & management'), ('finance', 'Finance & accounting'), ('law', 'Law'), ('political_science', 'Political science'), ('education', 'Education'), ('linguistics', 'Languages & linguistics'), ('literature', 'Literature'), ('history', 'History'), ('philosophy', 'Philosophy'), ('arts_design', 'Arts & design'), ('media_communication', 'Media & communication'), ('architecture', 'Architecture'), ('agriculture', 'Agriculture'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=40)),
                ('employment_status', models.CharField(blank=True, choices=[('student', 'Student'), ('employed', 'Employed'), ('self_employed', 'Self-employed'), ('unemployed', 'Not currently employed'), ('retired', 'Retired'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=24)),
                ('industry', models.CharField(blank=True, choices=[('agriculture', 'Agriculture & farming'), ('construction', 'Construction & real estate'), ('education', 'Education & research'), ('energy', 'Energy & utilities'), ('finance', 'Finance, banking & insurance'), ('government', 'Government & public sector'), ('healthcare', 'Healthcare & pharmaceuticals'), ('hospitality', 'Hospitality, travel & tourism'), ('it', 'Information technology & software'), ('legal', 'Legal & professional services'), ('manufacturing', 'Manufacturing & engineering'), ('marketing', 'Marketing, media & advertising'), ('nonprofit', 'Non-profit & NGO'), ('retail', 'Retail & e-commerce'), ('telecom', 'Telecommunications'), ('transport', 'Transport & logistics'), ('arts', 'Arts, culture & entertainment'), ('science', 'Science & biotechnology'), ('student', 'Student (not yet in a sector)'), ('other', 'Other industry'), ('prefer_not_to_say', 'Prefer not to say')], max_length=24)),
                ('income_bracket', models.CharField(blank=True, choices=[('lt_500', 'Under $500 / month'), ('500_1000', '$500 – $1,000 / month'), ('1000_2500', '$1,000 – $2,500 / month'), ('2500_5000', '$2,500 – $5,000 / month'), ('5000_10000', '$5,000 – $10,000 / month'), ('gt_10000', 'Over $10,000 / month'), ('prefer_not_to_say', 'Prefer not to say')], max_length=24)),
                ('religion', models.CharField(blank=True, choices=[('christianity', 'Christianity'), ('islam', 'Islam'), ('hinduism', 'Hinduism'), ('buddhism', 'Buddhism'), ('sikhism', 'Sikhism'), ('judaism', 'Judaism'), ('jainism', 'Jainism'), ('bahai', 'Bahá’í'), ('folk', 'Folk or traditional religion'), ('other', 'Other religion'), ('spiritual', 'Spiritual but not religious'), ('agnostic', 'Agnostic'), ('atheist', 'Atheist / no religion'), ('prefer_not_to_say', 'Prefer not to say')], max_length=24)),
                ('ethnicity', models.CharField(blank=True, choices=[('south_asian', 'South Asian'), ('east_asian', 'East Asian'), ('southeast_asian', 'Southeast Asian'), ('central_asian', 'Central Asian'), ('mena', 'Middle Eastern or North African'), ('black_african', 'Black or African'), ('white_european', 'White or European'), ('hispanic_latino', 'Hispanic or Latino'), ('indigenous', 'Indigenous or First Nations'), ('pacific_islander', 'Pacific Islander'), ('multiracial', 'Multiracial or mixed'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=24)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('occupation', models.CharField(blank=True, choices=[('student', 'Student'), ('researcher_academic', 'Researcher or academic'), ('engineer', 'Engineer'), ('software_developer', 'Software developer'), ('healthcare_professional', 'Healthcare professional'), ('educator_teacher', 'Educator or teacher'), ('manager_executive', 'Manager or executive'), ('entrepreneur', 'Entrepreneur or founder'), ('consultant', 'Consultant'), ('analyst', 'Analyst'), ('designer_creative', 'Designer or creative'), ('marketing_sales', 'Marketing or sales'), ('finance_professional', 'Finance professional'), ('legal_professional', 'Legal professional'), ('administrative', 'Administrative or clerical'), ('scientist', 'Scientist'), ('technician', 'Technician'), ('skilled_trades', 'Skilled trades'), ('service_worker', 'Service worker'), ('government_public', 'Government or public service'), ('nonprofit_worker', 'Non-profit worker'), ('retired', 'Retired'), ('homemaker', 'Homemaker'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=40)),
                ('institution', models.CharField(blank=True, max_length=160)),
                ('research_interests', models.JSONField(blank=True, default=list)),
                ('avatar', models.ImageField(blank=True, upload_to=accounts.models.profile_avatar_path, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp')), accounts.validators.validate_avatar_size])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_user_email_ci_unique'),
        ),
    ]
