# Generated by Django 5.2.16 on 2026-07-10 05:20

import accounts.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, validators=[accounts.validators.validate_birth_date])),
                ('gender', models.CharField(blank=True, choices=[('woman', 'Woman'), ('man', 'Man'), ('non_binary', 'Non-binary'), ('self_describe', 'Prefer to self-describe'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('gender_self_description', models.CharField(blank=True, max_length=80)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('education_level', models.CharField(blank=True, choices=[('secondary', 'Secondary school'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate or master’s'), ('doctorate', 'Doctorate'), ('vocational', 'Vocational or technical training'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=24)),
                ('field_of_study', models.CharField(blank=True, max_length=120)),
                ('employment_status', models.CharField(blank=True, choices=[('student', 'Student'), ('employed', 'Employed'), ('self_employed', 'Self-employed'), ('unemployed', 'Not currently employed'), ('retired', 'Retired'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=24)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('institution', models.CharField(blank=True, max_length=160)),
                ('research_interests', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
