# Generated by Django 5.2.16 on 2026-07-19 04:58

import accounts.models
import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=accounts.models.profile_avatar_path, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp')), accounts.validators.validate_avatar_size]),
        ),
    ]
