# Generated by Django 5.2.16 on 2026-07-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('south_asian', 'South Asian'), ('east_asian', 'East Asian'), ('southeast_asian', 'Southeast Asian'), ('central_asian', 'Central Asian'), ('mena', 'Middle Eastern or North African'), ('black_african', 'Black or African'), ('white_european', 'White or European'), ('hispanic_latino', 'Hispanic or Latino'), ('indigenous', 'Indigenous or First Nations'), ('pacific_islander', 'Pacific Islander'), ('multiracial', 'Multiracial or mixed'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=24),
        ),
        migrations.AddField(
            model_name='profile',
            name='income_bracket',
            field=models.CharField(blank=True, choices=[('lt_500', 'Under $500 / month'), ('500_1000', '$500 – $1,000 / month'), ('1000_2500', '$1,000 – $2,500 / month'), ('2500_5000', '$2,500 – $5,000 / month'), ('5000_10000', '$5,000 – $10,000 / month'), ('gt_10000', 'Over $10,000 / month'), ('prefer_not_to_say', 'Prefer not to say')], max_length=24),
        ),
        migrations.AddField(
            model_name='profile',
            name='industry',
            field=models.CharField(blank=True, choices=[('agriculture', 'Agriculture & farming'), ('construction', 'Construction & real estate'), ('education', 'Education & research'), ('energy', 'Energy & utilities'), ('finance', 'Finance, banking & insurance'), ('government', 'Government & public sector'), ('healthcare', 'Healthcare & pharmaceuticals'), ('hospitality', 'Hospitality, travel & tourism'), ('it', 'Information technology & software'), ('legal', 'Legal & professional services'), ('manufacturing', 'Manufacturing & engineering'), ('marketing', 'Marketing, media & advertising'), ('nonprofit', 'Non-profit & NGO'), ('retail', 'Retail & e-commerce'), ('telecom', 'Telecommunications'), ('transport', 'Transport & logistics'), ('arts', 'Arts, culture & entertainment'), ('science', 'Science & biotechnology'), ('student', 'Student (not yet in a sector)'), ('other', 'Other industry'), ('prefer_not_to_say', 'Prefer not to say')], max_length=24),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('christianity', 'Christianity'), ('islam', 'Islam'), ('hinduism', 'Hinduism'), ('buddhism', 'Buddhism'), ('sikhism', 'Sikhism'), ('judaism', 'Judaism'), ('jainism', 'Jainism'), ('bahai', 'Bahá’í'), ('folk', 'Folk or traditional religion'), ('other', 'Other religion'), ('spiritual', 'Spiritual but not religious'), ('agnostic', 'Agnostic'), ('atheist', 'Atheist / no religion'), ('prefer_not_to_say', 'Prefer not to say')], max_length=24),
        ),
    ]
