# Generated by Django 5.2.16 on 2026-07-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_ethnicity_profile_income_bracket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='field_of_study',
            field=models.CharField(blank=True, choices=[('computer_science', 'Computer science'), ('data_science', 'Data science & AI'), ('engineering', 'Engineering'), ('mathematics', 'Mathematics & statistics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology & life sciences'), ('environmental_science', 'Environmental science'), ('medicine', 'Medicine'), ('nursing', 'Nursing & allied health'), ('pharmacy', 'Pharmacy'), ('public_health', 'Public health'), ('psychology', 'Psychology'), ('sociology', 'Sociology & anthropology'), ('economics', 'Economics'), ('business', 'Business & management'), ('finance', 'Finance & accounting'), ('law', 'Law'), ('political_science', 'Political science'), ('education', 'Education'), ('linguistics', 'Languages & linguistics'), ('literature', 'Literature'), ('history', 'History'), ('philosophy', 'Philosophy'), ('arts_design', 'Arts & design'), ('media_communication', 'Media & communication'), ('architecture', 'Architecture'), ('agriculture', 'Agriculture'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('researcher_academic', 'Researcher or academic'), ('engineer', 'Engineer'), ('software_developer', 'Software developer'), ('healthcare_professional', 'Healthcare professional'), ('educator_teacher', 'Educator or teacher'), ('manager_executive', 'Manager or executive'), ('entrepreneur', 'Entrepreneur or founder'), ('consultant', 'Consultant'), ('analyst', 'Analyst'), ('designer_creative', 'Designer or creative'), ('marketing_sales', 'Marketing or sales'), ('finance_professional', 'Finance professional'), ('legal_professional', 'Legal professional'), ('administrative', 'Administrative or clerical'), ('scientist', 'Scientist'), ('technician', 'Technician'), ('skilled_trades', 'Skilled trades'), ('service_worker', 'Service worker'), ('government_public', 'Government or public service'), ('nonprofit_worker', 'Non-profit worker'), ('retired', 'Retired'), ('homemaker', 'Homemaker'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=40),
        ),
    ]
