# Generated by Django 5.2.16 on 2026-07-21 22:41

from django.db import migrations, models


def blank_legacy_free_text(apps, schema_editor):
    # research_interests was free text; reset every row to an empty JSON list
    # so the column holds valid JSON after the type change below.
    Profile = apps.get_model('accounts', 'Profile')
    Profile.objects.update(research_interests='[]')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_field_of_study_and_more'),
    ]

    operations = [
        migrations.RunPython(blank_legacy_free_text, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='research_interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
