# Generated by Django 5.2.16 on 2026-08-05 03:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('deleted', 'Permanently deleted')], max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='response_audit_events', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_audit_events', to='surveys.survey')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key_hash', models.CharField(db_index=True, max_length=64)),
                ('source', models.CharField(choices=[('direct', 'Direct link'), ('discover', 'Survey discover'), ('invitation', 'Respondent invitation')], default='direct', max_length=16)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], db_index=True, default='in_progress', max_length=16)),
                ('presentation', models.JSONField(default=dict)),
                ('identity_mode_snapshot', models.CharField(choices=[('anonymous', 'Anonymous to creator'), ('identified', 'Identified with consent')], default='anonymous', max_length=16)),
                ('identity_data', models.JSONField(blank=True, default=dict)),
                ('identity_consent_at', models.DateTimeField(blank=True, null=True)),
                ('is_eligible', models.BooleanField(default=True)),
                ('eligibility_data', models.JSONField(blank=True, default=dict)),
                ('eligibility_checked_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_submissions', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='surveys.survey')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='surveys.surveyversion')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='surveys.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='responses.submission')),
            ],
            options={
                'ordering': ('question__identity__section_identity__order', 'question__identity__order'),
            },
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'in_progress')), models.Q(('completed_at__isnull', False), ('status', 'completed')), _connector='OR'), name='responses_submission_status_timestamp_valid'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('respondent__isnull', False), ('status', 'completed')), fields=('survey', 'respondent'), name='responses_one_completed_per_user_survey'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'completed')), fields=('survey', 'session_key_hash'), name='responses_one_completed_per_session_survey'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='responses_one_answer_per_question'),
        ),
    ]
