# Generated by Django 5.2.16 on 2026-07-10 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0005_question_randomize_choices_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key_hash', models.CharField(db_index=True, max_length=64)),
                ('source', models.CharField(choices=[('direct', 'Direct link'), ('discovery', 'Survey discovery')], default='direct', max_length=16)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], db_index=True, default='in_progress', max_length=16)),
                ('presentation', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_submissions', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='surveys.survey')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='surveys.surveyversion')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='surveys.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='responses.submission')),
            ],
            options={
                'ordering': ('question__section__order', 'question__order'),
            },
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'in_progress')), models.Q(('completed_at__isnull', False), ('status', 'completed')), _connector='OR'), name='responses_submission_status_timestamp_valid'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='responses_one_answer_per_question'),
        ),
    ]
