# Generated by Django 5.2.16 on 2026-07-10 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
        ('surveys', '0005_question_randomize_choices_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='identity_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='identity_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('respondent__isnull', False), ('status', 'completed')), fields=('survey', 'respondent'), name='responses_one_completed_per_user_survey'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'completed')), fields=('survey', 'session_key_hash'), name='responses_one_completed_per_session_survey'),
        ),
    ]
