# Generated by Django 5.2.16 on 2026-07-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_submission_identity_consent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='eligibility_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='eligibility_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_eligible',
            field=models.BooleanField(default=True),
        ),
    ]
