# Generated by Django 5.2.16 on 2026-07-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0004_submission_excluded_at_submission_excluded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='source',
            field=models.CharField(choices=[('direct', 'Direct link'), ('discovery', 'Survey discovery'), ('invitation', 'Respondent invitation')], default='direct', max_length=16),
        ),
    ]
