# Generated by Django 5.2.16 on 2026-07-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0007_submission_identity_mode_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='excluded_at',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='excluded_by',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='exclusion_reason',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='is_excluded',
        ),
        migrations.AlterField(
            model_name='responseauditevent',
            name='action',
            field=models.CharField(
                choices=[('deleted', 'Permanently deleted')],
                max_length=16,
            ),
        ),
    ]
