# Generated by Django 5.2.16 on 2026-07-23 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0008_remove_submission_excluded_at_and_more'),
        ('surveys', '0012_require_snapshot_identities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseauditevent',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_audit_events', to='surveys.survey'),
        ),
    ]
