# Generated by Django 5.2.16 on 2026-08-05 03:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('responses', '0001_initial'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRewardClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_snapshot', models.PositiveIntegerField()),
                ('secret_hash', models.CharField(max_length=64)),
                ('session_key_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claimed_guest_rewards', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_reward_claim', to='responses.submission')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_reward_claims', to='surveys.survey')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('claimed_at__isnull', True), ('claimed_by__isnull', True)), models.Q(('claimed_at__isnull', False), ('claimed_by__isnull', False)), _connector='OR'), name='rewards_claim_status_consistent')],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(choices=[('profile_completion', 'Profile completion'), ('survey_completion', 'Survey completion')], max_length=32)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transaction', to='responses.submission')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='surveys.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='rewards_point_transaction_nonzero'), models.UniqueConstraint(condition=models.Q(('reason', 'survey_completion')), fields=('user', 'survey', 'reason'), name='rewards_one_completion_per_user_survey'), models.CheckConstraint(condition=models.Q(models.Q(('reason', 'profile_completion'), ('submission__isnull', True), ('survey__isnull', True)), models.Q(('reason', 'survey_completion'), ('survey__isnull', False)), models.Q(('reason', 'survey_completion'), ('submission__isnull', True), ('survey__isnull', True)), _connector='OR'), name='rewards_transaction_context_valid')],
            },
        ),
    ]
