# Generated by Django 5.2.16 on 2026-07-10 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0003_submission_eligibility_checked_at_and_more'),
        ('rewards', '0001_initial'),
        ('surveys', '0006_eligibilitycriteria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRewardClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_snapshot', models.PositiveIntegerField()),
                ('secret_hash', models.CharField(max_length=64)),
                ('session_key_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claimed_guest_rewards', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='guest_reward_claim', to='responses.submission')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_reward_claims', to='surveys.survey')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('claimed_at__isnull', True), ('claimed_by__isnull', True)), models.Q(('claimed_at__isnull', False), ('claimed_by__isnull', False)), _connector='OR'), name='rewards_claim_status_consistent')],
            },
        ),
    ]
