# Generated by Django 5.2.16 on 2026-07-10 13:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0003_submission_eligibility_checked_at_and_more'),
        ('rewards', '0002_guestrewardclaim'),
        ('surveys', '0006_eligibilitycriteria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=240)),
                ('completion_threshold', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ('completion_threshold',),
            },
        ),
        migrations.CreateModel(
            name='BadgeAward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-awarded_at',),
            },
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='point_transaction', to='responses.submission'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='point_transactions', to='surveys.survey'),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='reason',
            field=models.CharField(choices=[('profile_completion', 'Profile completion'), ('survey_completion', 'Survey completion')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='pointtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reason', 'survey_completion')), fields=('user', 'survey', 'reason'), name='rewards_one_completion_per_user_survey'),
        ),
        migrations.AddConstraint(
            model_name='pointtransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reason', 'profile_completion'), ('submission__isnull', True), ('survey__isnull', True)), models.Q(('reason', 'survey_completion'), ('submission__isnull', False), ('survey__isnull', False)), _connector='OR'), name='rewards_transaction_context_valid'),
        ),
        migrations.AddField(
            model_name='badgeaward',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='rewards.badge'),
        ),
        migrations.AddField(
            model_name='badgeaward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='badge_awards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='badgeaward',
            constraint=models.UniqueConstraint(fields=('user', 'badge'), name='rewards_one_badge_award_per_user'),
        ),
    ]
