# Generated by Django 5.2.16 on 2026-07-11 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0004_submission_excluded_at_submission_excluded_by_and_more'),
        ('rewards', '0004_seed_badges'),
        ('surveys', '0006_eligibilitycriteria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pointtransaction',
            name='rewards_transaction_context_valid',
        ),
        migrations.AlterField(
            model_name='guestrewardclaim',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_reward_claim', to='responses.submission'),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transaction', to='responses.submission'),
        ),
        migrations.AddConstraint(
            model_name='pointtransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reason', 'profile_completion'), ('submission__isnull', True), ('survey__isnull', True)), models.Q(('reason', 'survey_completion'), ('survey__isnull', False)), _connector='OR'), name='rewards_transaction_context_valid'),
        ),
    ]
