# Generated by Django 5.2.16 on 2026-07-23 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0009_alter_responseauditevent_survey'),
        ('rewards', '0005_remove_pointtransaction_rewards_transaction_context_valid_and_more'),
        ('surveys', '0012_require_snapshot_identities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pointtransaction',
            name='rewards_transaction_context_valid',
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='surveys.survey'),
        ),
        migrations.AddConstraint(
            model_name='pointtransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reason', 'profile_completion'), ('submission__isnull', True), ('survey__isnull', True)), models.Q(('reason', 'survey_completion'), ('survey__isnull', False)), models.Q(('reason', 'survey_completion'), ('submission__isnull', True), ('survey__isnull', True)), _connector='OR'), name='rewards_transaction_context_valid'),
        ),
    ]
