# Generated by Django 5.2.16 on 2026-08-05 03:04

import django.core.validators
import django.db.models.deletion
import surveys.models
import surveys.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MatrixRowIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('short_text', 'Short text'), ('long_text', 'Long text'), ('number', 'Number'), ('date', 'Date'), ('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('dropdown', 'Dropdown'), ('scale', 'Scale'), ('ranking', 'Ranking'), ('likert_matrix', 'Likert matrix')], max_length=24)),
                ('prompt', models.CharField(max_length=500)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('identity__order',),
            },
        ),
        migrations.CreateModel(
            name='QuestionIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('required', models.BooleanField(default=False)),
                ('randomize_choices', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('section_identity__order', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled section', max_length=160)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('identity__order',),
            },
        ),
        migrations.CreateModel(
            name='SectionIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('randomize_questions', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MatrixRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=240)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='surveys.matrixrowidentity')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_rows', to='surveys.question')),
            ],
            options={
                'ordering': ('identity__order',),
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=240)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='surveys.choiceidentity')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveys.question')),
            ],
            options={
                'ordering': ('identity__order',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='surveys.questionidentity'),
        ),
        migrations.AddField(
            model_name='matrixrowidentity',
            name='question_identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrix_row_identities', to='surveys.questionidentity'),
        ),
        migrations.AddField(
            model_name='choiceidentity',
            name='question_identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choice_identities', to='surveys.questionidentity'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='surveys.sectionidentity'),
        ),
        migrations.AddField(
            model_name='questionidentity',
            name='section_identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_identities', to='surveys.sectionidentity'),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(editable=False, max_length=180, unique=True)),
                ('summary', models.CharField(max_length=320)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('discoverable', 'Discoverable'), ('unlisted', 'Unlisted'), ('invitation_only', 'Invitation only')], default='discoverable', max_length=20)),
                ('identity_mode', models.CharField(choices=[('anonymous', 'Anonymous to creator'), ('identified', 'Identified with consent')], default='anonymous', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('banner', models.ImageField(blank=True, upload_to=surveys.models.survey_banner_path, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp')), surveys.validators.validate_survey_image_size])),
                ('thumbnail', models.ImageField(blank=True, upload_to=surveys.models.survey_thumbnail_path, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp')), surveys.validators.validate_survey_image_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('response_limit', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_surveys', to=settings.AUTH_USER_MODEL)),
                ('topics', models.ManyToManyField(blank=True, related_name='surveys', to='surveys.topic')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddField(
            model_name='sectionidentity',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_identities', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='questionidentity',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_identities', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='matrixrowidentity',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_row_identities', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='choiceidentity',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_identities', to='surveys.survey'),
        ),
        migrations.CreateModel(
            name='SurveyEligibilityCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(120)])),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(120)])),
                ('education_levels', models.JSONField(blank=True, default=list)),
                ('countries', models.JSONField(blank=True, default=list)),
                ('regions', models.JSONField(blank=True, default=list)),
                ('genders', models.JSONField(blank=True, default=list)),
                ('employment_statuses', models.JSONField(blank=True, default=list)),
                ('industries', models.JSONField(blank=True, default=list)),
                ('income_brackets', models.JSONField(blank=True, default=list)),
                ('religions', models.JSONField(blank=True, default=list)),
                ('ethnicities', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_criteria', to='surveys.survey')),
            ],
            options={
                'verbose_name_plural': 'survey eligibility criteria',
            },
        ),
        migrations.CreateModel(
            name='SurveyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=12)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('title_snapshot', models.CharField(blank=True, default='', max_length=160)),
                ('has_response_history', models.BooleanField(default=False)),
                ('response_limit', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_survey_versions', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='surveys.survey')),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.AddField(
            model_name='section',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='surveys.surveyversion'),
        ),
        migrations.CreateModel(
            name='SurveyBranchRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Does not equal'), ('contains', 'Contains'), ('answered', 'Is answered')], max_length=16)),
                ('compare_value', models.CharField(blank=True, max_length=240)),
                ('action', models.CharField(choices=[('go_to_section', 'Go to section'), ('end_survey', 'End survey')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('compare_choice_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comparison_branch_rules', to='surveys.choiceidentity')),
                ('source_question_identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_branch_rules', to='surveys.questionidentity')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_branch_rules', to='surveys.survey')),
                ('target_section_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_branch_rules', to='surveys.sectionidentity')),
            ],
            options={
                'ordering': ('order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('survey', 'order'), name='surveys_live_branch_rule_order_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='surveyversion',
            constraint=models.UniqueConstraint(fields=('survey', 'number'), name='surveys_version_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='surveyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('survey',), name='surveys_one_draft_version'),
        ),
        migrations.AddConstraint(
            model_name='surveyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('survey',), name='surveys_one_published_version'),
        ),
    ]
