# Generated by Django 5.2.16 on 2026-07-10 05:31

import django.core.validators
import django.db.models.deletion
import surveys.models
import surveys.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(editable=False, max_length=180, unique=True)),
                ('summary', models.CharField(max_length=320)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('discoverable', 'Discoverable'), ('unlisted', 'Unlisted'), ('invitation_only', 'Invitation only')], default='discoverable', max_length=20)),
                ('identity_mode', models.CharField(choices=[('anonymous', 'Anonymous to creator'), ('identified', 'Identified with consent')], default='anonymous', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('banner', models.ImageField(blank=True, upload_to=surveys.models.survey_banner_path, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp')), surveys.validators.validate_survey_image_size])),
                ('thumbnail', models.ImageField(blank=True, upload_to=surveys.models.survey_thumbnail_path, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp')), surveys.validators.validate_survey_image_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_surveys', to=settings.AUTH_USER_MODEL)),
                ('topics', models.ManyToManyField(blank=True, related_name='surveys', to='surveys.topic')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
