# Generated by Django 5.2.16 on 2026-07-10 05:31

from django.db import migrations


TOPICS = (
    ('Business and economics', 'business-economics'),
    ('Computer science', 'computer-science'),
    ('Education', 'education'),
    ('Environment and sustainability', 'environment-sustainability'),
    ('Mental health', 'mental-health'),
    ('Politics and governance', 'politics-governance'),
    ('Public health', 'public-health'),
    ('Science and engineering', 'science-engineering'),
    ('Social science', 'social-science'),
    ('Technology and society', 'technology-society'),
)


def create_topics(apps, schema_editor):
    topic_model = apps.get_model('surveys', 'Topic')
    topic_model.objects.bulk_create(
        [topic_model(name=name, slug=slug) for name, slug in TOPICS],
        ignore_conflicts=True,
    )


def remove_topics(apps, schema_editor):
    topic_model = apps.get_model('surveys', 'Topic')
    topic_model.objects.filter(slug__in=[slug for _, slug in TOPICS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_topics, remove_topics),
    ]
