# Generated by Django 5.2.16 on 2026-08-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_seed_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='requires_account',
            field=models.BooleanField(default=False),
        ),
    ]
