# Generated by Django 5.2.16 on 2026-07-10 05:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_seed_topics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled section', max_length=160)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('short_text', 'Short text'), ('long_text', 'Long text'), ('number', 'Number'), ('date', 'Date'), ('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('dropdown', 'Dropdown'), ('scale', 'Scale')], max_length=24)),
                ('prompt', models.CharField(max_length=500)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('config', models.JSONField(blank=True, default=dict)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.section')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='SurveyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=12)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_survey_versions', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='surveys.survey')),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.AddField(
            model_name='section',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='surveys.surveyversion'),
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=240)),
                ('order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveys.question')),
            ],
            options={
                'ordering': ('order',),
                'constraints': [models.UniqueConstraint(fields=('question', 'order'), name='surveys_choice_order_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('section', 'order'), name='surveys_question_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='surveyversion',
            constraint=models.UniqueConstraint(fields=('survey', 'number'), name='surveys_version_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='surveyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('survey',), name='surveys_one_draft_version'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('version', 'order'), name='surveys_section_order_unique'),
        ),
    ]
