# Generated by Django 5.2.16 on 2026-08-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_survey_requires_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='identity_scope',
            field=models.CharField(choices=[('contact', 'Name and email'), ('profile', 'Name, email and research profile')], default='contact', max_length=16),
        ),
    ]
