# Generated by Django 5.2.16 on 2026-07-10 05:36

from django.db import migrations


def create_initial_versions(apps, schema_editor):
    survey_model = apps.get_model('surveys', 'Survey')
    version_model = apps.get_model('surveys', 'SurveyVersion')
    section_model = apps.get_model('surveys', 'Section')

    for survey in survey_model.objects.iterator():
        if version_model.objects.filter(survey_id=survey.id).exists():
            continue
        version = version_model.objects.create(
            survey_id=survey.id,
            number=1,
            created_by_id=survey.owner_id,
        )
        section_model.objects.create(
            version_id=version.id,
            title='Section 1',
            order=1,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_section_question_surveyversion_section_version_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_versions, migrations.RunPython.noop),
    ]
