# Generated by Django 5.2.16 on 2026-08-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_survey_identity_scope'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='survey',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('identity_mode', 'identified'), ('identity_scope', 'profile'), _negated=True), ('requires_account', True), _connector='OR'), name='surveys_profile_sharing_requires_account'),
        ),
    ]
