# Generated by Django 5.2.16 on 2026-07-10 05:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_backfill_initial_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='randomize_choices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='randomize_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('short_text', 'Short text'), ('long_text', 'Long text'), ('number', 'Number'), ('date', 'Date'), ('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('dropdown', 'Dropdown'), ('scale', 'Scale'), ('ranking', 'Ranking'), ('likert_matrix', 'Likert matrix')], max_length=24),
        ),
        migrations.CreateModel(
            name='BranchRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Does not equal'), ('contains', 'Contains'), ('answered', 'Is answered')], max_length=16)),
                ('compare_value', models.CharField(blank=True, max_length=240)),
                ('action', models.CharField(choices=[('go_to_section', 'Go to section'), ('end_survey', 'End survey')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('source_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_rules', to='surveys.question')),
                ('target_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_branch_rules', to='surveys.section')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_rules', to='surveys.surveyversion')),
            ],
            options={
                'ordering': ('order',),
                'constraints': [models.UniqueConstraint(fields=('version', 'order'), name='surveys_branch_rule_order_unique')],
            },
        ),
        migrations.CreateModel(
            name='MatrixRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=240)),
                ('order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_rows', to='surveys.question')),
            ],
            options={
                'ordering': ('order',),
                'constraints': [models.UniqueConstraint(fields=('question', 'order'), name='surveys_matrix_row_order_unique')],
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('limit', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='surveys.surveyversion')),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('version', 'name'), name='surveys_quota_name_unique')],
            },
        ),
    ]
