# Generated by Django 5.2.16 on 2026-07-10 13:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_question_randomize_choices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(120)])),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(120)])),
                ('education_levels', models.JSONField(blank=True, default=list)),
                ('countries', models.JSONField(blank=True, default=list)),
                ('genders', models.JSONField(blank=True, default=list)),
                ('employment_statuses', models.JSONField(blank=True, default=list)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_criteria', to='surveys.surveyversion')),
            ],
            options={
                'verbose_name_plural': 'eligibility criteria',
            },
        ),
    ]
