# Generated by Django 5.2.16 on 2026-07-19 01:52

import django.core.validators
from django.db import migrations, models


def migrate_global_response_limits(apps, schema_editor):
    quota_model = apps.get_model('surveys', 'Quota')
    version_model = apps.get_model('surveys', 'SurveyVersion')
    for version in version_model.objects.iterator():
        limit = (
            quota_model.objects.filter(version_id=version.pk, is_active=True, criteria={})
            .order_by('limit')
            .values_list('limit', flat=True)
            .first()
        )
        if limit is not None:
            version_model.objects.filter(pk=version.pk).update(response_limit=limit)


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_survey_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyversion',
            name='response_limit',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.RunPython(migrate_global_response_limits, migrations.RunPython.noop),
    ]
