# Generated by Django 5.2.16 on 2026-07-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_surveyversion_response_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitycriteria',
            name='ethnicities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='eligibilitycriteria',
            name='income_brackets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='eligibilitycriteria',
            name='industries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='eligibilitycriteria',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='eligibilitycriteria',
            name='regions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='eligibilitycriteria',
            name='religions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
