# Generated by Django 5.2.16 on 2026-07-23 14:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_eligibilitycriteria_ethnicities_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MatrixRowIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuestionIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('required', models.BooleanField(default=False)),
                ('randomize_choices', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('section_identity__order', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SectionIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('randomize_questions', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SurveyBranchRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Does not equal'), ('contains', 'Contains'), ('answered', 'Is answered')], max_length=16)),
                ('compare_value', models.CharField(blank=True, max_length=240)),
                ('action', models.CharField(choices=[('go_to_section', 'Go to section'), ('end_survey', 'End survey')], max_length=20)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SurveyEligibilityCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(120)])),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(120)])),
                ('education_levels', models.JSONField(blank=True, default=list)),
                ('countries', models.JSONField(blank=True, default=list)),
                ('regions', models.JSONField(blank=True, default=list)),
                ('genders', models.JSONField(blank=True, default=list)),
                ('employment_statuses', models.JSONField(blank=True, default=list)),
                ('industries', models.JSONField(blank=True, default=list)),
                ('income_brackets', models.JSONField(blank=True, default=list)),
                ('religions', models.JSONField(blank=True, default=list)),
                ('ethnicities', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'survey eligibility criteria',
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='response_limit',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='has_response_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='title_snapshot',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddConstraint(
            model_name='surveyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('survey',), name='surveys_one_published_version'),
        ),
        migrations.AddField(
            model_name='choiceidentity',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_identities', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='surveys.choiceidentity'),
        ),
        migrations.AddField(
            model_name='matrixrowidentity',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_row_identities', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='matrixrow',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='surveys.matrixrowidentity'),
        ),
        migrations.AddField(
            model_name='questionidentity',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_identities', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='matrixrowidentity',
            name='question_identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrix_row_identities', to='surveys.questionidentity'),
        ),
        migrations.AddField(
            model_name='choiceidentity',
            name='question_identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choice_identities', to='surveys.questionidentity'),
        ),
        migrations.AddField(
            model_name='question',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='surveys.questionidentity'),
        ),
        migrations.AddField(
            model_name='sectionidentity',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_identities', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='questionidentity',
            name='section_identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_identities', to='surveys.sectionidentity'),
        ),
        migrations.AddField(
            model_name='section',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='surveys.sectionidentity'),
        ),
        migrations.AddField(
            model_name='surveybranchrule',
            name='compare_choice_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comparison_branch_rules', to='surveys.choiceidentity'),
        ),
        migrations.AddField(
            model_name='surveybranchrule',
            name='source_question_identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_branch_rules', to='surveys.questionidentity'),
        ),
        migrations.AddField(
            model_name='surveybranchrule',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_branch_rules', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='surveybranchrule',
            name='target_section_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_branch_rules', to='surveys.sectionidentity'),
        ),
        migrations.AddField(
            model_name='surveyeligibilitycriteria',
            name='survey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_criteria', to='surveys.survey'),
        ),
        migrations.AddConstraint(
            model_name='surveybranchrule',
            constraint=models.UniqueConstraint(fields=('survey', 'order'), name='surveys_live_branch_rule_order_unique'),
        ),
    ]
